name: Org Weely Stats
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 16 * * 1'

jobs:
  stats:
    name: Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: load Go 1.18 env
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: get org stats
        run: |
          go mod tidy
          go run .
        env:
          GITHUB_PAT_TOKEN: ${{ secrets.PAT }}
          GITHUB_ORG: ${{ secrets.STATS_ORG }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Commit report
        run: |
          git config --global user.name 'FDKevin'
          git config --global user.email 'fdkevinzero@gmail.com'
          git add -A
          git commit -m "weekly report ${{ steps.date.outputs.date }}"
          git push
      - name: release report
        uses: ncipollo/release-action@v1
        with:
          name: "${{ secrets.STATS_ORG }} weekly report ${{ steps.date.outputs.date }}"
          commit: main
          artifacts: "*.result,*.log"
          tag: ${{ steps.date.outputs.date }}
          bodyFile: "org-stats-${{ steps.date.outputs.date }}.result"
          token: ${{ secrets.GITHUB_TOKEN }}