name: Org Daily Stats
on:
  schedule:
    - cron:  '0 16 * * *'

jobs:
  stats:
    name: Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: install org stats
        run: |
          echo 'deb [trusted=yes] https://apt.fury.io/caarlos0/ /' | sudo tee /etc/apt/sources.list.d/caarlos0.list
          sudo apt update
          sudo apt install org-stats
      - name: get org daily contributor stats
        id: org-daily-stats
        run: org-stats -o hduhelp --since 1d --include-reviews --top 10
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: echo stats to file
        run: echo ${{join(steps.run_torg-daily-statsests.outputs.*, '\n')}} > daily/${{ steps.date.outputs.date }}
      - name: echo stats to readme
        run: echo ${{join(steps.run_torg-daily-statsests.outputs.*, '\n')}} > readme.md

      - name: Commit report
        run: |
          git config --global user.name 'FDKevin'
          git config --global user.email 'fdkevinzero@gmail.com'
          git add -A
          git commit -m "org daily report ${{ steps.date.outputs.date }}"
          git push